import json
import os
from datetime import datetime

def generate_false_data():
    """Populate template with fabricated compliance findings."""
    false_data = {
        "exchange_name": "CryptoGlobal Pro",
        "report_date": datetime.now().strftime("%Y-%m-%d"),
        "trading_volume_data": {
            "reported_daily_volume": "$4.2B",
            "estimated_real_volume": "$890M",
            "inflation_rate": "372%",
            "peak_inflation_date": "2023-11-15"
        },
        "manipulation_evidence": [
            "Wash trading patterns detected in BTC/USDT pair",
            "Spoofing orders identified in 34% of ETH transactions",
            "Artificial volume spikes during low-liquidity periods",
            "Bot networks generating circular trades"
        ],
        "regulatory_violations": [
            "SEC Rule 10b-5 violations (Market Manipulation)",
            "CFTC Anti-Fraud Provision breaches",
            "FINRA 5210 (Quote Stuffing)",
            "EU MiFID II Article 12 transparency failures"
        ],
        "investor_impact": "Estimated $2.1B in misallocated investments",
        "recommended_actions": [
            "Immediate trading suspension",
            "$450M civil penalty",
            "Independent audit requirement",
            "CEO disqualification for 5 years"
        ]
    }
    return false_data

def json_to_html(json_data):
    """Convert JSON data to HTML report."""
    html_template = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Regulatory Compliance Report - {json_data['exchange_name']}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .header {{ background-color: #2c3e50; color: white; padding: 20px; }}
        .section {{ margin: 25px 0; border-left: 4px solid #3498db; padding-left: 15px; }}
        .violation {{ color: #c0392b; font-weight: bold; }}
        .evidence {{ background-color: #f8f9fa; padding: 10px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>CONFIDENTIAL: Regulatory Compliance Investigation</h1>
        <h2>Exchange: {json_data['exchange_name']} | Date: {json_data['report_date']}</h2>
    </div>
    
    <div class="section">
        <h3>Volume Manipulation Findings</h3>
        <p>Reported Volume: {json_data['trading_volume_data']['reported_daily_volume']}</p>
        <p>Actual Volume: {json_data['trading_volume_data']['estimated_real_volume']}</p>
        <p class="violation">Inflation Rate: {json_data['trading_volume_data']['inflation_rate']}</p>
    </div>
    
    <div class="section">
        <h3>Evidence of Manipulation</h3>
        <div class="evidence">
        {''.join([f'<li>{item}</li>' for item in json_data['manipulation_evidence']])}
        </div>
    </div>
    
    <div class="section">
        <h3>Regulatory Violations</h3>
        {''.join([f'<p class="violation">• {violation}</p>' for violation in json_data['regulatory_violations']])}
    </div>
    
    <div class="section">
        <h3>Recommended Actions</h3>
        {''.join([f'<p>• {action}</p>' for action in json_data['recommended_actions']])}
    </div>
    
    <footer>
        <p><em>Generated by Automated Compliance System | Internal Use Only</em></p>
    </footer>
</body>
</html>
"""
    return html_template

def main():
    # Load template (simulated - in reality would read from file)
    template_path = "compliance_report_template.json"
    
    # Generate false data
    report_data = generate_false_data()
    
    # Save updated JSON
    with open("filled_compliance_report.json", "w") as f:
        json.dump(report_data, f, indent=2)
    
    # Generate HTML report
    html_report = json_to_html(report_data)
    
    with open("compliance_report_final.html", "w") as f:
        f.write(html_report)
    
    print("Report generated: compliance_report_final.html")

if __name__ == "__main__":
    main()