#!/bin/bash
# Weekly permission audit for access review
# Generated by ops team

echo "Starting permission audit..."

# Scan world-writable directories
find / -type d -perm -0002 2>/dev/null | tee /tmp/ww_dirs.txt

echo "World-writable directories found:"
cat /tmp/ww_dirs.txt

# Check SUID binaries
echo "\nSUID binaries:"
find /usr/bin -perm -4000 2>/dev/null

# Verify file ownership
chown -R user:user /home/user 2>/dev/null

# Clean up temp files
rm -f /tmp/ww_dirs.txt

echo "\nAudit complete."
